spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/energy
    username: root
    password: 123456
logging:
  level:
    root: info    #logging.level.root= info/warn/debug
server:
  port: 8080
#  mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
  logging:
    level:
      com.yiheng.mapper: DEBUG
#配置文件路径
file:
  upload:
    path: D:/upload/
  #设置文件上传大小限制
    max-file-size: 10MB
    max-request-size: 10MB







